import routex from "express-promise-router";
import CtrlArticulo from "../controllers/ArticuloController";
import auth from "../middleware/auth";
const router = routex();
router.post("/add", auth.verifyStorer, CtrlArticulo.add);
router.get("/query", auth.verifyStorer, CtrlArticulo.query);
router.get("/queryCodigo", auth.verifyUser, CtrlArticulo.queryCodigo);
router.get("/list", auth.verifyStorer, CtrlArticulo.list);
router.put("/update", auth.verifyStorer, CtrlArticulo.update);
router.put("/activate", auth.verifyStorer, CtrlArticulo.activate);
router.put("/deactivate", auth.verifyStorer, CtrlArticulo.deactivate);
router.delete("/remove", auth.verifyStorer, CtrlArticulo.remove);
module.exports = router;
