import routex from "express-promise-router";
import CtrlCategoria from "../controllers/CategoriaControllers";
import auth from "../middleware/auth";
const router = routex();
router.post("/add",auth.verifyStorer, CtrlCategoria.add);
router.get("/query",auth.verifyStorer, CtrlCategoria.query);
router.get("/list",auth.verifyStorer, CtrlCategoria.list);
router.put("/update",auth.verifyStorer, CtrlCategoria.update);
router.put("/activate",auth.verifyStorer, CtrlCategoria.activate);
router.put("/deactivate",auth.verifyStorer, CtrlCategoria.deactivate);
router.delete("/remove",auth.verifyStorer, CtrlCategoria.remove);
module.exports = router;
